name: Complete workflow

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node-version }}

      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          # node-version: ${{ matrix.node-version }}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "surf-forecast-beaches"
          heroku_email: "renanzdm@gmail.com"
          usedocker: true
    # - name: Start MongoDB
    #   uses: supercharge/mongodb-github-action@1.3.0
    #   with:
    #     mongodb-version: ${{ matrix.mongodb-version }}
    # - name: Install dependencies
    #   run: npm --frozen-lockfile
    # - name: Run all tests
    #   run: npm run tests
    # - shell: bash
    #   if: github.ref == 'refs/heads/main'
    #   name: Create SSH deployment key
    #   env:
    #     SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #   run: ./scripts/deploy.sh
    # - name: Deployment
    #   if: github.ref == 'refs/heads/main'
    #   run: git remote add umbler ssh://git@geonosis.deploy.umbler.com:9922/j6qpmw8e/storm-glass-forecast-com.git && git push umbler HEAD:master
    #   env:
    #     CI: true
